### ISSUE TITLE
Add support for interacting with file-based-catalogs

### ISSUE THREAD

**Issue by timflannagan** [timflannagan/platform-operators#3]
Goal: Add support for interacting with dedicated file-based-catalogs for an individual platform operator.

The implementation can either serve that file-based-catalog over a grpc connection, or use OLM's existing CatalogSource implementation, and communicate with a dedicated CatalogSource resource using the [registry ListBundles API](https://github.com/operator-framework/operator-registry/blob/38994ece779c79a6b238cff667810892c6df0d4e/pkg/registry/interface.go#L32) to get a list of olm.bundles that are present in that CatalogSource resource.

**Comment by tylerslaton** [comment]
That is technically support now in the current implementation as you can run any catalog and, so long as it has a valid grpc connection, it will connect. It only cares about a GRPC connection so the CatalogSource API is not required.
